version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 10

  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    expose:
      - $PORT
    depends_on:
      db:
        condition: service_healthy

  websocket:
    container_name: websocket-server
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run wss
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - $WSS_PORT
    ports:
      - $WSS_PORT:$WSS_PORT

volumes:
  postgres-volume:
