version: '3.8'
services:
  quiz-db:
    container_name: quiz-db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 10

  quiz-app:
    container_name: quiz-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      WSS_PORT: "$PORT" # Since we only need one server, we alias WSS_PORT to PORT
      POSTGRES_HOST: "quiz-db"
      POSTGRES_PORT: "5432"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@quiz-db:5432/${POSTGRES_DB}"
    volumes:
      - ./node_modules:/app/node_modules
    depends_on:
      quiz-db:
        condition: service_healthy
    expose:
      - $PORT
    ports:
      - $PORT:$PORT

volumes:
  postgres-volume: