import { NavbarContainer } from "@/components/nav";
import { QuizCreate } from "@/components/quizMutation";
import { Sortable } from "@/components/quizView";
import { authOptions } from "@/server/auth";
import type { GetServerSidePropsContext } from "next";
import { getServerSession, type Session } from "next-auth";
import Head from "next/head";

const Create = ({ userSession }: { userSession: Session }) => {
  console.log("🚀 ~ Create ~ userSession:", userSession);
  return (
    <>
      <Head>
        <title>Quizeroo - Create</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarContainer>
        <div className="flex flex-col gap-2">
          <Sortable />
          <QuizCreate />
        </div>
      </NavbarContainer>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const userSession = await getServerSession(
      context.req,
      context.res,
      authOptions,
    );

    if (!userSession?.user?.id) {
      return { redirect: { destination: "/", permanent: false } };
    }

    return { props: { userSession } };
  } catch (error) {
    console.error(error);
    return { redirect: { destination: "/", permanent: false } };
  }
}

export default Create;
