import { NavbarContainer } from "@/components/nav";
import { authOptions } from "@/server/auth";
import type { GetServerSidePropsContext } from "next";
import { getServerSession } from "next-auth";
import Head from "next/head";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Quizeroo - Dashboard</title>
        <meta name="description" content="Generated by Adiul Alam Adil" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarContainer>
        <div className="flex flex-col gap-2">dashboard page</div>
      </NavbarContainer>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const userSession = await getServerSession(
      context.req,
      context.res,
      authOptions,
    );

    if (!userSession?.user?.id) {
      return { redirect: { destination: "/", permanent: false } };
    }

    return { props: { userSession } };
  } catch (error) {
    console.error(error);
    return { redirect: { destination: "/", permanent: false } };
  }
}

export default Dashboard;
