import { DashboardCardsContainer } from "@/components/dashboard";
import { NavbarContainer } from "@/components/nav";
import { TempUserAlert } from "@/components/quizView";
import { H2 } from "@/components/ui/Typography";
import { authOptions } from "@/server/auth";
import type { GetServerSidePropsContext } from "next";
import { getServerSession, type Session } from "next-auth";
import Head from "next/head";

const Dashboard = ({ userSession }: { userSession: Session }) => {
  const { isTempUser } = userSession.user;

  return (
    <>
      <Head>
        <title>Quizeroo - Dashboard</title>
        <meta name="description" content="Generated by Adiul Alam Adil" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarContainer>
        <div className="flex w-full items-center justify-center">
          <div className="flex w-full max-w-7xl flex-col gap-4">
            <div className="flex flex-col gap-4 ">
              {isTempUser && <TempUserAlert />}
              <H2>Dashboard</H2>
            </div>
            <DashboardCardsContainer />
          </div>
        </div>
      </NavbarContainer>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const userSession = await getServerSession(
      context.req,
      context.res,
      authOptions,
    );

    if (!userSession?.user?.id) {
      return { redirect: { destination: "/", permanent: false } };
    }

    return { props: { userSession } };
  } catch (error) {
    console.error(error);
    return { redirect: { destination: "/", permanent: false } };
  }
}

export default Dashboard;
