// import { authOptions } from "@/server/auth";
// import { getSessionNameHandler } from "@/server/controller/quizSession.controller";
// import type { GetServerSidePropsContext } from "next";
// import { getServerSession } from "next-auth";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

const Join = () => {
  const session = useSession();
  console.log("🚀 ~ Join ~ session:", session);
  const router = useRouter();
  const id = router.query.id as string;
  console.log("🚀 ~ Join ~ router:", id);

  const [value, setValue] = useState("");

  const onClickHandler = async () => {
    console.log("🚀 ~ Join ~ value:", value);

    const response = await signIn("credentials", {
      username: value,
      quizSessionId: id,
      redirect: false,
    });
    console.log("🚀 ~ onClickHandler ~ response:", response);
  };

  return (
    <>
      <Head>
        <title>Quizeroo - Join</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Join {id}</p>
      <Input value={value} onChange={(e) => setValue(e.target.value)} />

      <Button onClick={onClickHandler}>Submit</Button>
    </>
  );
};

// export async function getServerSideProps(context: GetServerSidePropsContext) {
//   try {
//     const id = context.query.id;

//     const userSession = await getServerSession(
//       context.req,
//       context.res,
//       authOptions,
//     );

//     if (!userSession?.user?.id || typeof id !== "string") {
//       return { redirect: { destination: "/", permanent: false } };
//     }

//     const quizSession = await getSessionNameHandler({
//       input: { roomName: id },
//     });

//     return { props: { userSession, quizSession } };
//   } catch (error) {
//     console.error(error);
//     return { redirect: { destination: "/", permanent: false } };
//   }
// }

export default Join;
