import { JoinContainer } from "@/components/join";
import Head from "next/head";

const Join = () => {
  return (
    <>
      <Head>
        <title>Quizeroo - Join</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <JoinContainer />
    </>
  );
};

export default Join;
