name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies and Playwright binaries
        run: |
          npm install
          npx playwright install firefox
      - name: Setup environment variables
        run: |
          echo "NEXTAUTH_SECRET=supersecret" >> .env
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" >> .env
          echo "SKIP_ENV_VALIDATION=true" >> .env
      - name: Run Prisma migrations
        run: npm run db:migrate
      - name: Run Vitest unit tests
        run: npm run test:unit
      - name: Run Playwright e2e tests
        run: npm run test:e2e
